# Generated by Django 3.2.13 on 2022-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('total_price_HT', models.FloatField(null=True)),
                ('total_price_TTC', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('en préparation', 'en préparation'), ('expédié', 'expédié'), ('livré', 'livré'), ('retour client', 'retour client')], max_length=255, null=True)),
                ('Delivery_date_expected', models.DateTimeField(null=True)),
                ('Delivery_date_final', models.DateTimeField()),
            ],
        ),
    ]
