# Generated by Django 3.2.13 on 2022-06-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_total_HT',
            new_name='price_pdt_HT',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_total_TTC',
            new_name='price_pdt_TTC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.customer'),
        ),
    ]
