# Generated by Django 3.2.13 on 2022-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20220608_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_ordered_HT',
            field=models.ManyToManyField(db_column='price_pdt_HT', related_name='re_price_pdt_HT', to='Main.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='p_ordered_TTC',
            field=models.ManyToManyField(db_column='price_pdt_TTC', related_name='re_price_pdt_TTC', to='Main.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(db_column='name', related_name='re_name', to='Main.Product'),
        ),
    ]
