# Generated by Django 3.2.13 on 2022-06-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220608_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_ordered_HT',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_ordered_TTC',
        ),
    ]
