# Generated by Django 3.2.13 on 2022-06-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20220608_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price_HT',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_TTC',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_date_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
